services:
api:
  build:
    context:  .
    dockerfile: Dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - db
    environment:
     - ConnectionStrings__DefaultConnection=Server=db;Database=BloodBankDb;User=sa;Password=Your_password123;


db:
  image: mcr.microsoft.com/mssql/server
  container_name: sqlserver
  ports:
  - "1433:1433"
  environment:
    SA_PASSWORD: "Your_password123"
    ACCEPT_EULA: "Y"


